# Generated by Django 5.1.1 on 2025-01-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='kod',
            field=models.TextField(default='kod'),
        ),
    ]
