# Generated by Django 5.1.1 on 2025-01-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_content_kod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='kod',
            field=models.TextField(),
        ),
    ]
