# Generated by Django 5.1.1 on 2025-01-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_content_kod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='nomi',
            field=models.CharField(default='Nomi...', max_length=50),
        ),
    ]
