# Generated by Django 5.1.1 on 2025-01-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_content_nomi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='tili',
            field=models.CharField(choices=[('Python', 'Python'), ('Golang', 'Golang'), ('Java Script', 'Java Script'), ('Bat', 'Bat')], max_length=50),
        ),
    ]
