# Generated by Django 5.1.1 on 2025-01-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_content_tili'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='nimaga',
            field=models.CharField(choices=[('Softwere', 'Softwere'), ('raspberry-pi', 'raspberry-pi'), ('Arduino', 'Arduino'), ('USB', 'USB'), ('Bluetooth', 'Bluetooth')], default='Hech nima', max_length=50),
        ),
    ]
