# Generated by Django 5.1.1 on 2025-01-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_content_nimaga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='nimaga',
            field=models.CharField(choices=[('Softwere', 'Softwere'), ('raspberry-pi', 'raspberry-pi'), ('Arduino', 'Arduino'), ('USB', 'USB'), ('Bluetooth', 'Bluetooth')], max_length=50),
        ),
    ]
